### ISSUE TITLE
`ValkyrieRunningTemplateProvider` may cause problems

### ISSUE THREAD

**Issue by ForNeVeR** [nyar-vm/valkyrie-intellij#5]
Hello! I am a maintainer of the IntelliJ PowerShell plugin, and have been recently investigating an issue related to a `RunConfigurationTemplateProvider` implementation in the plugin: https://github.com/ant-druha/intellij-powershell/issues/138

What I found is that the template provider is not really required for your run configuration to support the templates, and it even wreaks havoc and breaks their support.

I'd recommend you to take a look at the steps I was using to reproduce the issue (it's pretty straightforward, I'll reproduce them below), and consider removing `ValkyrieRunningTemplateProvider` completely: the run configurations should only start working better after that.

Out of curiosity, I'd like to ask you how you find that interface and why you decided to implement it in the first place.

Steps to reproduce:

1. Create a new project.
2. Open the **Edit Configurations** dialog window.
3. Press the **Edit configuration templates…** in the left bottom corner.
4. Edit your plugin's run configuration template, e.g. set the working directory or any other parameter.
5. Reopen the run configuration template editor, observe that the new parameters weren't loaded for the template (the template looks fresh again), even though they are persisted in `.idea/workspace.xml`.
6. Create a new configuration, observe how the templated parameters aren't set.

Suggested fix: remove `ValkyrieRunningTemplateProvider`.

**Comment by oovm** [comment]
I have disabled the feature and submitted a new version, but reviews may be slower on weekends.

**Comment by oovm** [comment]
The new version has passed the review. I don't know what the old users should do. I don't see the function of canceling a published version.
